----------------
Creating a JWS App secret - Prerequisite
----------------
In order to get a JWS app to build properly a JWS App Secret needs to exist.
If there isn’t a JWS certificate needed to build the app outside of STI then a substitute can be used. 
Otherwise you can use you own in the steps that follow.

-Get a copy of the JWS App Secret .json file from the JBoss Openshift Git repo:
  https://github.com/jboss-openshift/application-templates/blob/master/secrets/jws-app-secret.json
-Save the file locally on the OSE Master node. 
  If you have a JWS App Certificate and Key you can replace the “server.crt” and “server.key” lines.
-Execute the following command:
  oc create -f <file you created above>
-Add the Secret to the Builder ServiceAccount:
  oc secrets add serviceaccount/builder secret/jws-app-secret

-------------------
Using a private repository
-------------------
When using a Private Repo the Deploy Key needs to be available for the build process 
so it can execute a Git Clone command against the repo.

-If a key has not been created for the Master Node run the following command:
ssh-keygen -t rsa
-Use the ~/.ssh/id_rsa.pub file to create a Deploy Key for the private repo
  This can be done through the UI for the repo by an admin
-Create a new Secret using the private key created above:
  oc secrets new amgen-git ssh-privatekey=$HOME/.ssh/id_rsa -n <project name>
-Add the new secret to the Builder service account:
 oc secrets add serviceaccount/builder secrets/amgen-git -n <project name>
 
 

